# Generated by Django 6.0 on 2026-06-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("tigo_pesa", "Tigo Pesa"),
                            ("airtel_money", "Airtel Money"),
                            ("halo_pesa", "Halo Pesa"),
                            ("manual", "Manual Payment"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#0891b2", max_length=20)),
                ("description", models.TextField()),
                ("recipient_name", models.CharField(max_length=200)),
                ("recipient_phone", models.CharField(max_length=20)),
                (
                    "recipient_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recipient_bank",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("instructions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_confirmed", "Payment Confirmed"),
                            ("payment_verified", "Payment Verified"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("status_update", "Status Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("email_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("sender_name", models.CharField(max_length=200)),
                ("sender_phone", models.CharField(max_length=20)),
                ("sender_email", models.EmailField(max_length=254)),
                (
                    "sender_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("receiver_name", models.CharField(max_length=200)),
                ("receiver_phone", models.CharField(max_length=20)),
                (
                    "receiver_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "receiver_bank",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("screenshot_base64", models.TextField(blank=True, null=True)),
                (
                    "screenshot_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "screenshot_content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("verified", "Verified"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("whatsapp_sent", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="payments.paymentmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_code", models.CharField(max_length=50, unique=True)),
                ("customer", models.CharField(blank=True, max_length=300, null=True)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_phone", models.CharField(max_length=20)),
                ("customer_email", models.EmailField(max_length=254)),
                ("requested_service", models.CharField(max_length=200)),
                ("request_description", models.TextField(blank=True, null=True)),
                (
                    "budget_minimum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_maximum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="paymentsession",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="PaymentWebhook",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.AddField(
            model_name="paymentnotification",
            name="payment_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="payments.paymentrecord",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="service_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.servicerequest",
            ),
        ),
        migrations.DeleteModel(
            name="PaymentSession",
        ),
    ]
