# Generated by Django 6.0 on 2026-06-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentmethod_paymentnotification_paymentrecord_and_more"),
        ("registration", "0007_remove_customerservicerequest_transaction_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
