# Generated by Django 6.0 on 2026-06-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(default="CRDB Bank PLC", max_length=100),
                ),
                (
                    "account_name",
                    models.CharField(default="QuickFix Services", max_length=200),
                ),
                (
                    "account_number",
                    models.CharField(default="01-1234567890", max_length=50),
                ),
                ("branch", models.CharField(default="Kariakoo Branch", max_length=100)),
                ("swift_code", models.CharField(default="CORUTZTZ", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bank Details",
                "verbose_name_plural": "Bank Details",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentnotification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment Notification",
                "verbose_name_plural": "Payment Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment Record",
                "verbose_name_plural": "Payment Records",
            },
        ),
        migrations.AlterModelOptions(
            name="servicerequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
            },
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="method_type",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="recipient_account",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="recipient_bank",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="recipient_name",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="recipient_phone",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="email_sent",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="receiver_bank",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="sender_email",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="verified_at",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="customer",
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="api_method",
            field=models.CharField(default="mpesa", max_length=50),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="transaction_info",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="proof_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="proof_uri",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="status_display",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="formatted_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="formatted_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="request_status_display",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="color",
            field=models.CharField(default="#4CAF50", max_length=20),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="icon",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_method",
            field=models.CharField(default="mpesa", max_length=20),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="service_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.servicerequest",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
