# Generated by Django 6.0 on 2026-06-29 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_bankdetails_alter_paymentmethod_options_and_more"),
        ("registration", "0008_remove_customerservicerequest_payment_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="service_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="registration.customerservicerequest",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="sender_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ServiceRequest",
        ),
    ]
