# Generated by Django 6.0 on 2025-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_booking_booking_number_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garageservice',
            name='service',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
