# Generated by Django 6.0 on 2025-12-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_garageservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garageservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service'),
        ),
    ]
