# Generated by Django 6.0 on 2025-12-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_garageservice_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_detail',
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.service'),
        ),
    ]
