# Generated by Django 6.0 on 2025-12-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_booking_options_remove_booking_service_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
