# Generated by Django 6.0 on 2025-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_service_garage_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='location_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='location_detection_method',
            field=models.CharField(blank=True, choices=[('ip', 'IP Address'), ('browser', 'Browser Geolocation'), ('manual', 'Manually Entered'), ('failed', 'Failed to Detect')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
