# Generated by Django 6.0 on 2025-12-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_booking_address_booking_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location_detected',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location_detection_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='longitude',
        ),
    ]
