# Generated by Django 6.0 on 2025-12-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
