# Generated by Django 6.0 on 2025-12-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('garage_owner', 'Garage Owner'), ('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
