# Generated by Django 6.0 on 2026-01-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_booking_options_booking_discount_booking_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="discount",
        ),
    ]
