# Generated by Django 6.0 on 2026-01-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_booking_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="users.service",
            ),
        ),
    ]
