# Generated by Django 6.0 on 2026-01-06 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_booking_service"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="users_booki_mobile__2cb671_idx",
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user"], name="users_booki_user_id_499425_idx"),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="mobile_number",
        ),
    ]
