# Generated by Django 6.0 on 2026-01-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_remove_booking_users_booki_mobile__2cb671_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_method",
            field=models.CharField(
                choices=[
                    ("email", "Email Only"),
                    ("phone", "Phone Only"),
                    ("both", "Both Email & Phone"),
                ],
                default="both",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="User's email address (optional if phone is provided)",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                help_text="User's phone number (optional if email is provided)",
                max_length=15,
                unique=True,
            ),
        ),
    ]
