# Generated by Django 6.0 on 2026-03-07 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_garage_address_alter_garageservice_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garage",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="garageservice",
            name="duration",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="garageservice",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="base_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="color",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="servicedetail",
            name="duration",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="servicedetail",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
