# Generated by Django 6.0 on 2026-05-13 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("location_address", models.TextField(blank=True, null=True)),
                (
                    "location_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "request_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "appointment_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("new_status", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Approval Record",
                "verbose_name_plural": "Approval Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["request_code", "-created_at"],
                        name="registratio_request_e81a11_idx",
                    ),
                    models.Index(
                        fields=["appointment_code", "-created_at"],
                        name="registratio_appoint_70f0b7_idx",
                    ),
                    models.Index(
                        fields=["updated_by"], name="registratio_updated_d893a4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AutoWorkshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workshop_name", models.CharField(max_length=255)),
                ("workshop_email", models.EmailField(max_length=254)),
                ("workshop_phone", models.CharField(max_length=20)),
                ("workshop_address", models.TextField()),
                (
                    "workshop_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "workshop_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "workshop_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_workshop_verified", models.BooleanField(default=False)),
                ("is_workshop_active", models.BooleanField(default=True)),
                ("workshop_created", models.DateTimeField(auto_now_add=True)),
                ("workshop_updated", models.DateTimeField(auto_now=True)),
                (
                    "workshop_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workshops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Workshop",
                "verbose_name_plural": "Auto Workshops",
            },
        ),
        migrations.CreateModel(
            name="CustomerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("requested_service", models.CharField(max_length=255)),
                ("request_description", models.TextField(blank=True, null=True)),
                (
                    "vehicle_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vehicle_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vehicle_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "vehicle_color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "license_plate",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("service_location", models.TextField()),
                ("location_maps_link", models.URLField(blank=True, null=True)),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("preferred_service_date", models.DateField()),
                ("preferred_service_time", models.TimeField()),
                ("is_urgent_request", models.BooleanField(default=False)),
                (
                    "request_urgency",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("priority", "Priority"),
                            ("emergency", "Emergency"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "budget_minimum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_maximum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_budget_flexible", models.BooleanField(default=True)),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("awaiting", "Awaiting Offers"),
                            ("viewed", "Viewed by Workshops"),
                            ("offers_received", "Offers Received"),
                            ("accepted", "Offer Accepted"),
                            ("in_progress", "Service in Progress"),
                            ("completed", "Service Completed"),
                            ("cancelled", "Request Cancelled"),
                            ("expired", "Request Expired"),
                        ],
                        default="awaiting",
                        max_length=20,
                    ),
                ),
                ("offer_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("times_viewed", models.IntegerField(default=0)),
                ("customer_notes", models.TextField(blank=True, null=True)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone_call", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="phone_call",
                        max_length=20,
                    ),
                ),
                ("request_expires", models.DateTimeField()),
                ("request_created", models.DateTimeField(auto_now_add=True)),
                ("request_updated", models.DateTimeField(auto_now=True)),
                (
                    "accepted_workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_customer_requests",
                        to="registration.autoworkshop",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Service Request",
                "verbose_name_plural": "Customer Service Requests",
                "ordering": ["-request_created"],
            },
        ),
        migrations.CreateModel(
            name="RepairService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_title", models.CharField(max_length=255)),
                ("service_description", models.TextField(blank=True, null=True)),
                (
                    "service_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_base_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_service_active", models.BooleanField(default=True)),
                ("service_created", models.DateTimeField(auto_now_add=True)),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provided_services",
                        to="registration.autoworkshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repair Service",
                "verbose_name_plural": "Repair Services",
            },
        ),
        migrations.CreateModel(
            name="WorkshopQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quoted_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_duration", models.PositiveIntegerField(default=1)),
                ("workshop_notes", models.TextField(blank=True, null=True)),
                (
                    "quote_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted by Customer"),
                            ("declined", "Declined by Customer"),
                            ("withdrawn", "Withdrawn by Workshop"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("quote_created", models.DateTimeField(auto_now_add=True)),
                ("quote_updated", models.DateTimeField(auto_now=True)),
                (
                    "customer_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_quotes",
                        to="registration.customerrequest",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provided_quotes",
                        to="registration.autoworkshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Quote",
                "verbose_name_plural": "Workshop Quotes",
                "ordering": ["quoted_price", "quote_created"],
                "unique_together": {("customer_request", "workshop")},
            },
        ),
        migrations.CreateModel(
            name="ServiceAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("appointment_service", models.CharField(max_length=255)),
                ("service_details", models.TextField(blank=True, null=True)),
                ("agreed_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "appointment_vehicle_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "appointment_vehicle_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "appointment_vehicle_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "appointment_license_plate",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("appointment_location", models.TextField()),
                ("appointment_maps_link", models.URLField(blank=True, null=True)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed by Workshop"),
                            ("in_progress", "Service in Progress"),
                            ("completed", "Service Completed"),
                            ("cancelled", "Appointment Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("appointment_notes", models.TextField(blank=True, null=True)),
                ("sms_confirmation_sent", models.BooleanField(default=False)),
                (
                    "sms_confirmation_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sms_reminder_sent", models.BooleanField(default=False)),
                ("sms_reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("appointment_created", models.DateTimeField(auto_now_add=True)),
                ("appointment_updated", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_appointment",
                        to="registration.customerrequest",
                    ),
                ),
                (
                    "service_workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="registration.autoworkshop",
                    ),
                ),
                (
                    "accepted_quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="registration.workshopquote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Appointment",
                "verbose_name_plural": "Service Appointments",
                "ordering": ["-appointment_date", "-appointment_created"],
            },
        ),
    ]
