# Generated by Django 6.0 on 2026-05-13 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approve",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="serviceappointment",
            options={"ordering": ["-appointment_date", "-appointment_created"]},
        ),
        migrations.AlterModelOptions(
            name="workshopquote",
            options={"ordering": ["quoted_price", "quote_created"]},
        ),
        migrations.RemoveIndex(
            model_name="approve",
            name="registratio_request_e81a11_idx",
        ),
        migrations.RemoveIndex(
            model_name="approve",
            name="registratio_appoint_70f0b7_idx",
        ),
        migrations.RemoveIndex(
            model_name="approve",
            name="registratio_updated_d893a4_idx",
        ),
        migrations.AlterField(
            model_name="customerrequest",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
