# Generated by Django 6.0 on 2026-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrequest",
            name="email_cancelled_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="email_cancelled_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="email_created_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="email_created_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="email_status_change_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="email_status_change_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="email_updated_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="email_updated_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_cancelled_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_cancelled_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_created_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_created_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_status_change_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_status_change_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_updated_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="sms_updated_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_cancelled_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_cancelled_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_confirmation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_status_update_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="email_status_update_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="sms_cancelled_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="sms_cancelled_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="sms_status_update_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="sms_status_update_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="email_accepted_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="email_accepted_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="email_offer_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="email_offer_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="sms_accepted_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="sms_accepted_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="sms_offer_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workshopquote",
            name="sms_offer_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
