# Generated by Django 6.0 on 2026-05-13 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_approve_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "customer_name",
                    models.CharField(help_text="Full name of customer", max_length=255),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        help_text="Phone number for contact", max_length=20
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("requested_service", models.CharField(max_length=255)),
                ("request_description", models.TextField(blank=True, null=True)),
                (
                    "vehicle_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vehicle_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vehicle_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "vehicle_color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "license_plate",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("service_location", models.TextField()),
                ("location_maps_link", models.URLField(blank=True, null=True)),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("preferred_service_date", models.DateField()),
                ("preferred_service_time", models.TimeField()),
                ("is_urgent_request", models.BooleanField(default=False)),
                (
                    "request_urgency",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("priority", "Priority"),
                            ("emergency", "Emergency"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "budget_minimum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_maximum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_budget_flexible", models.BooleanField(default=True)),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("customer_notes", models.TextField(blank=True, null=True)),
                ("request_created", models.DateTimeField(auto_now_add=True)),
                ("request_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Service Request",
                "verbose_name_plural": "Customer Service Requests",
                "ordering": ["-request_created"],
            },
        ),
        migrations.AlterField(
            model_name="workshopquote",
            name="customer_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="serviceappointment",
            name="customer_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_appointment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="CustomerRequest",
        ),
    ]
