# Generated by Django 6.0 on 2026-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_remove_customerrequest_email_cancelled_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceappointment",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the appointment was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="Name of admin/manager who approved the appointment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="fixed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the service was marked as completed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceappointment",
            name="fixed_by",
            field=models.CharField(
                blank=True,
                help_text="Name of technician/admin who completed the service",
                max_length=255,
                null=True,
            ),
        ),
    ]
