# Generated by Django 6.0 on 2026-05-13 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_customerservicerequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Garage/Workshop name", max_length=255),
                ),
                ("address", models.TextField(help_text="Full address of the garage")),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City name", max_length=100, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average rating (0-5)",
                        max_digits=3,
                    ),
                ),
                (
                    "rating_count",
                    models.IntegerField(
                        default=0, help_text="Number of ratings received"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="Currently open for business"
                    ),
                ),
                (
                    "delivery_available",
                    models.BooleanField(
                        default=False, help_text="Offers mobile/delivery service"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Verified by admin"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active garage"),
                ),
                (
                    "estimated_time",
                    models.CharField(
                        default="15-30 mins",
                        help_text="Estimated service time",
                        max_length=100,
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True, default=list, help_text="List of services offered"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operating hours for each day",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Garage owner (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_garages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Garage",
                "verbose_name_plural": "Garages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="registratio_name_2f9f56_idx"),
                    models.Index(fields=["city"], name="registratio_city_9d8552_idx"),
                    models.Index(
                        fields=["is_active", "is_open"],
                        name="registratio_is_acti_ed75ec_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="registratio_latitud_5be60a_idx",
                    ),
                ],
            },
        ),
    ]
