# Generated by Django 6.0 on 2026-05-21 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_garage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerservicerequest",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the request was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="Who approved this request",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="fixed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the request was fixed/completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="fixed_by",
            field=models.CharField(
                blank=True,
                help_text="Who fixed/completed this request",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="updated_by",
            field=models.CharField(
                blank=True,
                help_text="Last person who updated the request",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerservicerequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("viewed", "Viewed"),
                    ("offers_received", "Offers Received"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="serviceappointment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="serviceappointment",
            name="customer_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_appointment",
                to="registration.customerservicerequest",
            ),
        ),
        migrations.AlterField(
            model_name="workshopquote",
            name="customer_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="registration.customerservicerequest",
            ),
        ),
    ]
