# Generated by Django 6.0 on 2026-04-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_serviceappointment_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceappointment",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="serviceappointment",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="serviceappointment",
            name="fixed_at",
        ),
        migrations.RemoveField(
            model_name="serviceappointment",
            name="fixed_by",
        ),
    ]
