# Generated by Django 6.0 on 2026-04-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_remove_serviceappointment_approved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fixed_by", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Approve",
                "verbose_name_plural": "Approvals",
                "ordering": ["-created_at"],
            },
        ),
    ]
