# Generated by Django 6.0 on 2026-05-26 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("registration", "0005_customerservicerequest_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerservicerequest",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated payment transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_request",
                to="payments.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="customerservicerequest",
            name="budget_maximum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Automatically set from payment transaction",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerservicerequest",
            name="budget_minimum",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
