# Generated by Django 6.0 on 2026-04-06 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_approve"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approve",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Approval Record",
                "verbose_name_plural": "Approval Records",
            },
        ),
        migrations.RemoveField(
            model_name="approve",
            name="fixed_by",
        ),
        migrations.AddField(
            model_name="approve",
            name="appointment_code",
            field=models.CharField(
                blank=True,
                help_text="Associated appointment code",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="customer_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_records",
                to="registration.customerrequest",
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="new_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="approve",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Any additional notes about the update", null=True
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="approve",
            name="previous_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="approve",
            name="request_code",
            field=models.CharField(
                blank=True,
                help_text="Associated request code",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="service_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_records",
                to="registration.serviceappointment",
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("request_status", "Customer Request Status"),
                    ("appointment_status", "Appointment Status"),
                    ("quote_status", "Quote Status"),
                ],
                default="request_status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="updated_by",
            field=models.CharField(
                help_text="Name of person who made the update",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["customer_request", "-created_at"],
                name="registratio_custome_2dd04d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["service_appointment", "-created_at"],
                name="registratio_service_43286c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["updated_by"], name="registratio_updated_d893a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["request_code"], name="registratio_request_19a4b6_idx"
            ),
        ),
    ]
