# Generated by Django 6.0 on 2026-06-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentmethod_paymentnotification_paymentrecord_and_more"),
        ("registration", "0006_customerservicerequest_transaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerservicerequest",
            name="transaction",
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="payment_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated payment record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="payments.paymentrecord",
            ),
        ),
        migrations.CreateModel(
            name="RegistrationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("service_fee", "Service Fee"),
                            ("deposit", "Deposit"),
                            ("full_payment", "Full Payment"),
                            ("refund", "Refund"),
                        ],
                        default="full_payment",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="TZS", max_length=10)),
                ("sender_name", models.CharField(max_length=200)),
                ("sender_phone", models.CharField(max_length=20)),
                ("sender_email", models.EmailField(max_length=254)),
                ("receiver_name", models.CharField(max_length=200)),
                ("receiver_phone", models.CharField(max_length=20)),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_transactions",
                        to="payments.paymentrecord",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_transactions",
                        to="registration.customerservicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Transaction",
                "verbose_name_plural": "Registration Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
