# Generated by Django 6.0 on 2026-06-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_remove_customerservicerequest_transaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerservicerequest",
            name="payment_record",
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                help_text="Status of the associated payment",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Associated payment transaction ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerservicerequest",
            name="transaction_reference",
            field=models.CharField(
                blank=True,
                help_text="Payment transaction reference",
                max_length=100,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="RegistrationTransaction",
        ),
    ]
