# Generated by Django 6.0 on 2026-04-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_alter_approve_options_remove_approve_fixed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approve",
            name="updated_by",
            field=models.CharField(
                default="System User",
                help_text="Name of person who made the update",
                max_length=200,
            ),
        ),
    ]
