# Generated by Django 6.0 on 2026-04-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_alter_approve_updated_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="approve",
            name="registratio_custome_2dd04d_idx",
        ),
        migrations.RemoveIndex(
            model_name="approve",
            name="registratio_service_43286c_idx",
        ),
        migrations.RemoveIndex(
            model_name="approve",
            name="registratio_request_19a4b6_idx",
        ),
        migrations.AlterField(
            model_name="approve",
            name="appointment_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="approve",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approve",
            name="request_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="approve",
            name="updated_by",
            field=models.CharField(
                blank=True,
                help_text="Name of person who made the update",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["request_code", "-created_at"],
                name="registratio_request_e81a11_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="approve",
            name="customer_request",
        ),
        migrations.RemoveField(
            model_name="approve",
            name="service_appointment",
        ),
        migrations.RemoveField(
            model_name="approve",
            name="update_type",
        ),
    ]
