# Generated by Django 6.0 on 2026-04-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_remove_approve_registratio_custome_2dd04d_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["appointment_code", "-created_at"],
                name="registratio_appoint_70f0b7_idx",
            ),
        ),
    ]
