# Generated by Django 6.0 on 2026-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_approve_registratio_appoint_70f0b7_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="approve",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="location_address",
            field=models.TextField(
                blank=True,
                help_text="Formatted address or location description",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="location_city",
            field=models.CharField(
                blank=True, help_text="City name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="location_country",
            field=models.CharField(
                blank=True, help_text="Country name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="approve",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["latitude", "longitude"], name="registratio_latitud_22b941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approve",
            index=models.Index(
                fields=["location_city"], name="registratio_locatio_1228f8_idx"
            ),
        ),
    ]
