# Generated by Django 6.0 on 2026-05-12 09:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("estimated_duration", models.DurationField(blank=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "garage_name",
                    models.CharField(
                        blank=True, default="", help_text="Garage name", max_length=255
                    ),
                ),
                (
                    "garage_phone",
                    models.CharField(
                        blank=True, default="", help_text="Garage phone", max_length=20
                    ),
                ),
                (
                    "garage_email",
                    models.EmailField(
                        blank=True, default="", help_text="Garage email", max_length=254
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="City/Location",
                        max_length=200,
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                (
                    "experience",
                    models.TextField(
                        help_text="User's description of their experience and service needs",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "service_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vehicle_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("vehicle_year", models.IntegerField(blank=True, null=True)),
                (
                    "vehicle_make",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vehicle_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received by Garage"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("agreed_to_terms", models.BooleanField(default=False)),
                ("terms_agreement_date", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quote_approved", models.BooleanField(default=False)),
                ("quote_approved_date", models.DateTimeField(blank=True, null=True)),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("user_feedback", models.TextField(blank=True, default="")),
                ("garage_notes", models.TextField(blank=True, default="")),
                ("vehicle_photos", models.JSONField(blank=True, default=list)),
                (
                    "invoice_document",
                    models.FileField(
                        blank=True, null=True, upload_to="service_invoices/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("sms_confirmation_sent", models.BooleanField(default=False)),
                (
                    "sms_confirmation_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sms_status_update_sent", models.BooleanField(default=False)),
                (
                    "sms_status_update_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sms_reminder_sent", models.BooleanField(default=False)),
                ("sms_reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_confirmation_sent", models.BooleanField(default=False)),
                (
                    "email_confirmation_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("email_status_update_sent", models.BooleanField(default=False)),
                (
                    "email_status_update_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("is_emergency", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered user (if logged in)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="service_request_attachments/%Y/%m/%d/"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_attachments",
                        to="mechanics.servicerequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Attachment",
                "verbose_name_plural": "Service Request Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True,
                        help_text="If True, note is visible only to staff/garage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_notes",
                        to="mechanics.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Note",
                "verbose_name_plural": "Service Request Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("priority_change", "Priority Change"),
                            ("quote_provided", "Quote Provided"),
                            ("quote_approved", "Quote Approved"),
                            ("note_added", "Note Added"),
                            ("completion", "Service Completed"),
                            ("cancellation", "Cancellation"),
                            ("assignment", "Assigned to Staff"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("old_value", models.CharField(blank=True, default="", max_length=255)),
                ("new_value", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_updates",
                        to="mechanics.servicerequest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Update",
                "verbose_name_plural": "Service Request Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["status", "created_at"], name="mechanics_s_status_696408_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["created_at"], name="mechanics_s_created_7a5046_idx"
            ),
        ),
    ]
