# Generated by Django 6.0 on 2026-01-02 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0001_initial"),
        ("users", "0021_alter_booking_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        help_text="City/Location from form", max_length=200
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        help_text="User's description of their experience and service needs",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of service needed (auto-detected from experience or user-selected)",
                        max_length=100,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of vehicle (e.g., Sedan, SUV, Truck)",
                        max_length=100,
                    ),
                ),
                ("vehicle_year", models.IntegerField(blank=True, null=True)),
                ("vehicle_make", models.CharField(blank=True, max_length=100)),
                ("vehicle_model", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received by Garage"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("agreed_to_terms", models.BooleanField(default=False)),
                ("terms_agreement_date", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost provided by garage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual cost after service completion",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("quote_approved", models.BooleanField(default=False)),
                ("quote_approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True, help_text="User rating (1-5)", null=True
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True, help_text="User feedback after service"
                    ),
                ),
                (
                    "garage_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from garage staff"
                    ),
                ),
                (
                    "vehicle_photos",
                    models.JSONField(
                        blank=True, default=list, help_text="List of photo URLs"
                    ),
                ),
                (
                    "invoice_document",
                    models.FileField(
                        blank=True, null=True, upload_to="service_invoices/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("is_emergency", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "garage",
                    models.ForeignKey(
                        help_text="Selected garage from the form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="users.garage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered user (if logged in)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="service_request_attachments/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mechanics.servicerequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Attachment",
                "verbose_name_plural": "Service Request Attachments",
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("priority_change", "Priority Change"),
                            ("quote_provided", "Quote Provided"),
                            ("quote_approved", "Quote Approved"),
                            ("note_added", "Note Added"),
                            ("completion", "Service Completed"),
                            ("cancellation", "Cancellation"),
                            ("assignment", "Assigned to Staff"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="mechanics.servicerequest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Update",
                "verbose_name_plural": "Service Request Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("estimated_duration", models.DurationField(blank=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "garages",
                    models.ManyToManyField(
                        blank=True, related_name="service_types", to="users.garage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
                "ordering": ["name"],
            },
        ),
        migrations.DeleteModel(
            name="MechanicRequest",
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["status", "created_at"], name="mechanics_s_status_696408_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["garage", "status"], name="mechanics_s_garage__11ba41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["user", "created_at"], name="mechanics_s_user_id_4e395e_idx"
            ),
        ),
    ]
