# Generated by Django 6.0 on 2026-05-13 04:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequestattachment",
            name="service_request",
        ),
        migrations.RemoveField(
            model_name="servicerequestattachment",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="address",
            field=models.TextField(blank=True, default="", help_text="Full address"),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="email_to_garage_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="email_to_garage_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="license_plate",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="garage_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Garage email (will receive notifications)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user_rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="servicerequestupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("created", "Request Created"),
                    ("status_change", "Status Change"),
                    ("priority_change", "Priority Change"),
                    ("quote_provided", "Quote Provided"),
                    ("quote_approved", "Quote Approved"),
                    ("note_added", "Note Added"),
                    ("completion", "Service Completed"),
                    ("cancellation", "Cancellation"),
                    ("assignment", "Assigned to Garage"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["garage_email"], name="mechanics_s_garage__a3ad26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["email"], name="mechanics_s_email_24c5df_idx"),
        ),
        migrations.DeleteModel(
            name="ServiceRequestAttachment",
        ),
    ]
