# Generated by Django 6.0 on 2026-05-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0002_remove_servicerequestattachment_service_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="profile_picture",
            field=models.TextField(
                blank=True, help_text="Base64 or URL of profile picture", null=True
            ),
        ),
    ]
