# Generated by Django 6.0 on 2026-01-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0002_servicerequest_servicerequestattachment_and_more"),
        ("users", "0021_alter_booking_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="garage",
            field=models.ForeignKey(
                help_text="Selected garage from the form",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="garage_service_requests",
                to="users.garage",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Registered user (if logged in)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_service_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequestattachment",
            name="service_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_attachments",
                to="mechanics.servicerequest",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequestupdate",
            name="service_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_updates",
                to="mechanics.servicerequest",
            ),
        ),
    ]
