# Generated by Django 6.0 on 2026-01-07 06:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0003_alter_servicerequest_garage_and_more"),
        ("users", "0022_remove_booking_users_booki_mobile__2cb671_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicerequestattachment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Service Request Attachment",
                "verbose_name_plural": "Service Request Attachments",
            },
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="actual_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="experience",
            field=models.TextField(
                default="",
                help_text="User's description of their experience and service needs",
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="garage",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected garage from the form",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="garage_service_requests",
                to="users.garage",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="garage_notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="location",
            field=models.CharField(
                default="", help_text="City/Location", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user_agent",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user_feedback",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_make",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_model",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_photos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequestattachment",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="servicerequestattachment",
            name="file",
            field=models.FileField(upload_to="service_request_attachments/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="servicerequestattachment",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("photo", "Photo"),
                    ("document", "Document"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                default="document",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequestupdate",
            name="new_value",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="servicerequestupdate",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="servicerequestupdate",
            name="old_value",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="servicerequestupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status Change"),
                    ("priority_change", "Priority Change"),
                    ("quote_provided", "Quote Provided"),
                    ("quote_approved", "Quote Approved"),
                    ("note_added", "Note Added"),
                    ("completion", "Service Completed"),
                    ("cancellation", "Cancellation"),
                    ("assignment", "Assigned to Staff"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="ServiceRequestNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True,
                        help_text="If True, note is visible only to staff/garage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_notes",
                        to="mechanics.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Note",
                "verbose_name_plural": "Service Request Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
