# Generated by Django 6.0 on 2026-01-07 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0004_alter_servicerequestattachment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="experience",
            field=models.TextField(
                help_text="User's description of their experience and service needs",
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="garage_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="location",
            field=models.CharField(
                blank=True, default="", help_text="City/Location", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_make",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
