# Generated by Django 6.0 on 2026-03-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mechanics",
            "0005_alter_servicerequest_city_alter_servicerequest_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="email_confirmation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="email_confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="email_status_update_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="email_status_update_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sms_confirmation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sms_confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sms_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sms_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sms_status_update_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sms_status_update_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
