# Generated by Django 6.0 on 2026-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otpverification",
            options={},
        ),
        migrations.AddField(
            model_name="otpverification",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name="otpverification",
            table=None,
        ),
    ]
