# Generated by Django 6.0 on 2026-05-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authe", "0002_alter_otpverification_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otpverification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="otpverification",
            name="mobile_number",
        ),
        migrations.AlterModelTable(
            name="otpverification",
            table="otp_verifications",
        ),
    ]
