# Generated by Django 6.0 on 2026-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authe", "0003_alter_otpverification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("mechanic", "Mechanic"),
                            ("garage_owner", "Garage Owner"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
            },
        ),
        migrations.AddField(
            model_name="myprofile",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="User roles",
                related_name="profiles",
                to="authe.role",
            ),
        ),
    ]
