# Generated by Django 6.0 on 2026-05-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authe", "0004_role_myprofile_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myprofile",
            name="roles",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
