# Generated by Django 6.0 on 2026-05-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authe", "0005_remove_myprofile_roles_delete_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("mechanic", "Mechanic"),
                    ("garage_owner", "Garage Owner"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="customer",
                max_length=20,
            ),
        ),
    ]
